package.json

Added configuration with command to copy examples.

Resolved problem with build

---

README.md

I read this & added some suggestions on what I found to read slightly easier. Also fixed a few typos

Spelling suggestions in readme

---

src/interfaces/control/Labels.js
src/interfaces/control/RectangleLabels.js
src/interfaces/mixins/Control.js
src/interfaces/mixins/LabelMixin.js
src/interfaces/object/AudioPlus.js
src/stores/CompletionStore.js

- Mixin of Labels and RectangleLabels

HOC of controls

---

docs/themes/htx/layout/partials/index.ejs
docs/themes/htx/source/js/common.js

it says lunch a few places on the site and I think it should be launch.

fixing lunch->launch typos

---

docs/source/tags/shortcut.md
docs/themes/htx/layout/layout.ejs
package-lock.json
package.json
src/components/App/App.js
src/core/Hotkey.js
src/core/Tree.js
src/interfaces/control/Shortcut.js
src/interfaces/control/TextArea.js
src/interfaces/object/TextAreaRegion.js
src/interfaces/visual/View.js
src/stores/CompletionStore.js
src/stores/SettingsStore.js

* Use xml2js instead of parse5 for tree building
* HotKey support for shortcuts

* Add Shortcut tag to simplify adding predefined objects

---

backend/server.py
backend/utils/db.py

Now we can point to local directory, e.g.
```
python server.py --input-path local/directory/with/images
```
and we recursively convert all images to labeling tasks
https://github.com/heartexlabs/label-studio/issues/107

Streaming images from local dir

---

label_studio/utils/misc.py

To fix issue https://github.com/heartexlabs/label-studio/issues/173
`required` is not a valid argument for `add_subparsers`

fix broken cli

---

label_studio/project.py
label_studio/server.py
label_studio/static/js/lsb.js
label_studio/templates/tasks.html
label_studio/utils/argparser.py
requirements.txt
setup.py

- expose `--sampling` option in CLI and UI
- adding "Skip" button in label stream
- fix startup failing when root-dir is specified
https://github.com/heartexlabs/label-studio/issues/240 https://github.com/heartexlabs/label-studio/issues/227

CMD opt sampling, skip button, root_dir fix

---

Dockerfile
app.json

Hi all, this fixes the one click deployment to google cloud run.

Fix one click deploy

---

label_studio/server.py
label_studio/utils/argparser.py

Signed-off-by: Leonardo Rossi <leonardo.rossi@studenti.unipr.it>

server: host as optional parameter

---

label_studio/tasks.py

Fix task counter while reading from text file

---

label_studio/static/js/lsb.js
label_studio/templates/base.html
label_studio/templates/export.html
label_studio/templates/labeling.html
label_studio/templates/model.html
label_studio/templates/render_ls.html
label_studio/templates/setup.html
label_studio/templates/setup_help.html
label_studio/templates/tasks.html
label_studio/templates/welcome.html
label_studio/utils/io.py

- update JS, HTML pages for proxied safety
- attempts to fix issue #273; now works with or without a proxy

fix URL paths for proxy safety

---

label_studio/examples/text_multi_class/config.xml
label_studio/server.py
label_studio/templates/export.html
requirements.txt

- Local paths now supported for VOC/COCO export formats
Fixed issues:
https://github.com/heartexlabs/label-studio/issues/281

Pre release 0.7.0 fixes

---

label_studio/templates/base.html

add senty script to base template
to catch all  uncaught errors

add ls-opensource sentry config

---

docs/source/guide/ml.md

directory is technically label-studio/label_studio/ml/examples

fixing directory

---

docs/themes/htx/layout/partials/index.ejs
label_studio/__init__.py
requirements.txt

label-studio-converter version fix.

Release 0.7.4.post0

---

label_studio/project.py
label_studio/server.py

because most `completed_at` are not used.

Minimum formatting of completed_at

---

label_studio/project.py

they are maintained in source storage

Don't keep premade predictions in completion

---

label_studio/blueprint.py

analytics instance is in globals, not in project

Fix api_predict

---

docs/source/guide/storage.md

Updated the doc format to standardize and clarify, adding UI steps, plus added extra details about redis config params that I'm not totally sure (but like 80% sure) are correct based on /storage/redis.py. @makseq please take a look!

Update storage.md with more detail

---

README.md

@Asjidkalam (https://huntr.dev/users/Asjidkalam) has fixed a potential Arbitrary Code Execution vulnerability in your repository 🔨. For more information, visit our website (https://huntr.dev/) or click the bounty URL below...
Q | A
Version Affected | *
Bug Fix | YES
Original Pull Request | https://github.com/418sec/label-studio/pull/1
Vulnerability README | https://github.com/418sec/huntr/blob/master/bounties/pip/label-studio/1/README.md
Insecure YAML desearilization
`Label Studio` is a swiss army knife of data labeling and annotation tools which is vulnerable to Arbitrary Code Execution.
Vulnerable to YAML deserialization attack caused by unsafe loading.
* `pip3 install label-studio`
`python3 exp.py`
```python3
import os
#os.sysem('pip3 install label-studio')
from label_studio.utils …
```

Security Fix for Arbitrary Code Execution - huntr.dev

---

docs/themes/htx/layout/partials/index.ejs
label_studio/utils/misc.py

When start server it hang on port checking, so I add timeout when checking port with default value 10 seconds.

Fixed start local server hang when check port

---

docs/source/guide/FAQ.md
docs/source/guide/api.md
docs/source/guide/export.md
docs/source/guide/index.md
docs/source/guide/install.md
docs/source/guide/labeling.md
docs/source/guide/ml.md
docs/source/guide/setup.md
docs/source/guide/storage.md
docs/source/guide/tasks.md

Updating content to be more quickstart/overview oriented.
After reading this page I can explain to my colleague which parts of Label Studio I might want to extend
After reading this page I can map out the steps of a data labeling project that I need to prepare for.

Rearchitect and update docs

---

docs/themes/htx/layout/partials/header.ejs
docs/themes/htx/source/css/new-header.css
docs/themes/htx/source/css/new-styles.css

- Reduce headers height
- Highlight current page
- Use grey background for top menu

Small fixes to website headers

---

label_studio/core/label_config.py
label_studio/core/utils/contextlog.py
label_studio/core/utils/io.py
label_studio/data_export/models.py
label_studio/data_import/models.py
label_studio/projects/api.py
label_studio/server.py
label_studio/tests/test_api_integration.py
label_studio/tests/test_data/gen_tasks_and_annotations.py

If not using utf-8, this will cause error on some platforms, for example Windows especially in China.

Using utf-8 as default encoding

---

docs/source/guide/signup.md

Invite link doc updates

---

deploy/dockerfiles/subpath.example.yml
docs/source/guide/start.md
setup.py

Added a couple notes in the start doc to refer to the docker example, updated text for the messages too.

Updates for relative URLs

---

docs/source/guide/install.md

Adding examples of how to install Label Studio using a virtual environment with pip and on Ubuntu

Add venv examples

---

label_studio/io_storages/all_api.py
label_studio/io_storages/localfiles/models.py
label_studio/io_storages/localfiles/serializers.py
label_studio/io_storages/urls.py

This PR aims to enable the use of a local folder of the server as a local storage by allowing the API to access the classes required to do so, with some slight corrections.

Enable local files export storage support

---

docs/source/guide/index.md
docs/source/guide/labeling.md
docs/source/guide/predictions.md

* How to filter and sort tasks on data manager
* Use cases for doing that to affect labeling
* Updating predictions example JSON to include a score
* random edits to the index page

Adding task filtering details

---

label_studio/users/templates/users/user_account.html
label_studio/users/templates/users/user_login.html
label_studio/users/templates/users/user_signup.html

Some assets host path did not respect host setting.
Signed-off-by: Even Wei <evenwei@infuseai.io>

Fix template assets path

---

label_studio/templates/401.html
label_studio/templates/403.html
label_studio/templates/404.html
label_studio/templates/500.html
label_studio/templates/base.html
label_studio/templates/drf-yasg/redoc.html
label_studio/users/templates/password/password_reset_form.html
label_studio/users/templates/users/user_login.html

1. patch template assets host path
2. fix typo of `rel="shortcut icon"` in `base.html`
Signed-off-by: Even Wei <evenwei@infuseai.io>

fix template assets host path

---

docs/source/guide/signup.md
docs/source/guide/start.md

Adding examples about starting label studio with environment variables for various deployment scenarios

Adding env var info for user/pass

---

label_studio/projects/models.py

https://github.com/heartexlabs/label-studio/issues/895

Fix deleting task with relation

---

docs/source/guide/export.md
docs/source/tutorials/dummy_model.md
docs/source/tutorials/gpt.md
docs/source/tutorials/nemo_asr.md
docs/source/tutorials/object-detector.md
docs/source/tutorials/pytorch-image-transfer-learning.md
docs/source/tutorials/sklearn-text-classifier.md

Cleaning up language, and making sure steps are accurate for all the ML tutorials, especially the NeMo tutorial.

ML tutorial fixes

---

deploy/wait-for-postgres.sh
docker-compose.yml

update wait-for-postgres.sh for better experience
- wait-for-postgres.sh read parameters from the environment 
- Keep the same value-name with dockercompose.yaml

[update] update wait-for-postgres.sh for better experience

---

README.md
docs/themes/htx/layout/page.ejs

Update Slack link in docs footer

---

docs/source/guide/security.md
docs/source/guide/storage.md

Add details about S3 external ID and IAM role

---

label_studio/frontend/src/components/Form/Form.js

Boolean fields disappeared from FormData when unchecked

Fix boolean fields in forms [checkbox]

---

.black
.pylintrc

Using black like autoformater:
https://github.com/psf/black
Using pylint like linter:
https://github.com/PyCQA/pylint

Common lint/autoformat config

---

docs/source/guide/storage.md

Improve target storage and S3 information based on customer feedback
Add clarity to GCS credentials based on customer feedback and comments

Update storage docs

---

label_studio/organizations/api.py
label_studio/projects/api.py
label_studio/tasks/api.py

Change get_queryset to filter_queryset for applying general

---

label_studio/io_storages/azure_blob/form_layout.yml
label_studio/io_storages/gcs/form_layout.yml
label_studio/io_storages/s3/form_layout.yml
label_studio/io_storages/s3/models.py
label_studio/io_storages/s3/utils.py
label_studio/tests/io_storages.tavern.yml

*Fixes*:
- S3 TTL is not propagated
- Missed TTL description in Cloud Storage settings forms

[fix] s3 TTL & cloud storage form settings

---

docs/source/blog/Evaluating-Named-Entity-Recognition-parsers-with-spaCy-and-Label-Studio.md

Fixes #1277 typo in NER code 😢

Update NER blog

---

label_studio/frontend/package-lock.json

https://github.com/heartexlabs/label-studio/issues/1063

Update package-lock.json to a newer version

---

label_studio/projects/api.py
label_studio/tasks/api.py
label_studio/tasks/serializers.py

[ext] Add deprecation warning about meta field removing from task model

---

docs/package-lock.json
docs/package.json

Fixing #1063: critical vulnerabilities found in `docs/` section
Thanks @dalekube for reporting.

[fix] Docs deps vulnerabilities

---

docs/source/templates/audio_classification.md
docs/source/templates/audio_regions.md
docs/source/templates/dialogue_analysis.md
docs/source/templates/html_document.md
docs/source/templates/image_bbox.md
docs/source/templates/image_ellipse.md
docs/source/templates/image_keypoints.md
docs/source/templates/image_polygons.md
docs/source/templates/image_segmentation.md
docs/source/templates/index.md
docs/source/templates/named_entity.md
docs/source/templates/pairwise_comparison.md
docs/source/templates/sentiment_analysis.md
docs/source/templates/time_series.md
docs/source/templates/transcribe_audio.md

Will overhaul template docs soon, this is just to remove deprecated option and provide an alternative.
Fixes #1278

Remove --template flag

---

docs/package-lock.json
docs/package.json
label_studio/frontend/package-lock.json
label_studio/frontend/package.json

Another round of fixing frontend vulnerabilities in `docs/` and `label_studio/frontend`
Fixes: #1063

Frontend vulnerabilities

---

docs/source/guide/storage.md

- Add trust policy and role policies for S3 bucket storage with IAM role 
- Add recursive scan option from 1.2.0 to S3 docs

Update S3 IAM role info

---

label_studio/data_manager/api.py

[fix] Stop resolving uri without storages

---

label_studio/data_import/api.py
label_studio/data_import/models.py
label_studio/data_import/urls.py

[fix] Change UploadFile names "project_id-hash-orig_fname"

---

docs/source/guide/api_migrate.md

Responding to customer feedback + confusion resulting from inaccurate response example

Clarify API migrate export endpoint

---

docs/source/guide/storage.md

Add target storage sync

---

label_studio/annotation_templates/structured-data-parsing/pdf-classification/config.xml
label_studio/annotation_templates/structured-data-parsing/pdf-classification/config.yml

Later I'll add fixes for audio templates

[fix] use inline="true" for PDF template

---

label_studio/frontend/src/providers/ApiProvider.js

Sometimes when server hangs LS might end in an infinite loop causing black screen of death and complete freeze of the browser.
This PR fixes this issue.

[fix] Black screen of death

---

docs/source/guide/ml.md
docs/source/guide/ml_create.md
docs/source/guide/predictions.md

- Clarify variable details for create ML doc
- Correct errors about how model versions work for displaying predictions
- Add IDs to text example in predictions doc
- Add troubleshooting example for nested labeling and predictions

Update ML docs about predictions

---

docs/source/guide/quality.md
docs/source/guide/setup.md

- Update docs to match UI for ground truth annotations
- Add details about filtering and showing ground truth info on data manager
- Remove bulk assign ground truth option

[docs] Update ground truth info

---

label_studio/io_storages/azure_blob/models.py
label_studio/io_storages/base_models.py
label_studio/io_storages/gcs/models.py
label_studio/io_storages/models.py
label_studio/io_storages/s3/models.py
label_studio/tasks/models.py

Ability to resolve URL links from multiple connected storage

[ext] Resolve multiple storage URI

---

docs/source/guide/labeling.md

- Add label tasks as displayed details
- Update hotkeys to be accurate
- Add details about multi-select for regions
- Clarify delete an annotation vs delete a region

Update labeling info in docs

---

docs/source/guide/storage.md

- Clarify what an S3 endpoint is/whether it's needed
- Update role permissions info for regular S3
- Add more details about access key ID etc.

[docs] Clarify role permissions and S3 endpoint

---

docs/themes/htx/layout/partials/header.ejs

[docs] update menu text

---

docs/source/guide/custom_metric.md

Docs for LSE custom agreement metric in private cloud AWS EC2/EKS

Docs for custom agreement metric for private cloud LSE

---

docs/themes/htx/layout/partials/heartex_header.ejs

Matching the overall website change to emphasize LSE 2.1 over Teams

Update docs header

---

docs/source/guide/install_enterprise.md
docs/source/guide/sdk.md
docs/themes/htx/layout/partials/header.ejs

SDK tutorial for the docs with short code examples. Please check my code examples and let me know if the ones I've chosen make sense. 
I'll make a note of which ones to mention in links from other docs accordingly, and set that up in a different PR (e.g., a link in the project docs about how to create a project from a python script with the SDK)

DEV-438: SDK tutorial

---

docs/source/guide/api.md

Removing pre-1.0.0 docs and updating page accordingly

DEV-1195: Updating API doc to drop pre-1.0.0 API docs

---

docs/source/templates/gallery_asr.html
docs/source/templates/gallery_conversational_ai.html
docs/source/templates/gallery_cv.html
docs/source/templates/gallery_data_parsing.html
docs/source/templates/gallery_nlp.html
docs/source/templates/gallery_rns.html
docs/source/templates/gallery_timeseries.html
docs/source/templates/gallery_videos.html
docs/themes/htx/layout/partials/toc.ejs

- fix audio/speech processing
- add galleries to TOC since removing order doesn't exclude them

[docs] DEV-1466 Fix templates TOC

---

docs/source/guide/ml.md
docs/source/guide/ml_create.md
docs/source/guide/ml_troubleshooting.md

Automating pipelines with webhooks and refactor the ML docs a bit.

DEV-1100 — Add details about webhooks with ML backends

---

label_studio/core/feature_flags/base.py

FEATURE_FLAGS_DEFAULT_VALUE  => downloaded_feature_flags.yml || [launchdarkly.com](http://launchdarkly.com/) if available => user env => [LS]

fix: DEV-1724: Add priority to env var for feature flags

---

docs/source/templates/content_image_retrieval.md
docs/source/templates/document_retrieval.md
docs/source/templates/pairwise_comparison.md
docs/source/templates/pairwise_regression.md

* Streamline interactive template preview
* Add "about this template" section

Docs: DEV-1717 — Enhance ranking & scoring templates

---

docs/source/templates/freeform_metadata.md
docs/source/templates/html_document.md
docs/source/templates/pdf_classification.md
docs/source/templates/tabular_data.md

- streamline interactive template text
- add about the template section explaining tags

Docs: DEV-1717 — Enhance structured data parsing templates

---

docs/source/templates/coreference_entity_linking.md
docs/source/templates/response_generation.md
docs/source/templates/response_selection.md
docs/source/templates/slot_filling.md

- Streamline interactive template preview
- Add "about this template" section 
- Add xlink for coreference resolution and entity linking to relation extraction

Docs: DEV-1717 — Enhance conversational AI templates

---

docs/source/templates/machine_translation.md
docs/source/templates/named_entity.md
docs/source/templates/question_answering.md
docs/source/templates/relation_extraction.md
docs/source/templates/sentiment_analysis.md
docs/source/templates/taxonomy.md
docs/source/templates/text_summarization.md

- Add details about templates
- Add enhancement notes to NER template for putting labels on the left
- Streamline interactive template display and remove one

Docs: DEV-1717 — Enhance NLP templates

---

docs/source/templates/video_classification.md
docs/source/templates/video_timeline_segmentation.md

* Streamline preview content
* Add details about both current video labeling configs

Docs: DEV-1717 — Enhance video templates

---

label_studio/data_manager/actions/predictions_to_annotations.py
label_studio/webhooks/models.py
label_studio/webhooks/utils.py

fix: DEV-1725: Add ANNOTATIONS_CREATED webhook action to predictions to annotations action

---

label_studio/data_manager/actions/__init__.py

* only load expected python files

fix: Label-studio will not start in previously working environment #2245

---

label_studio/organizations/models.py
label_studio/tests/test_invites.py
label_studio/users/views.py

* disallow if token does not match

fix: DEV-2233: Insecure invite token expiration

---

label_studio/tasks/models.py

* fix: DEV-2406: Fix counters for skipped annotations
* Fixes
Co-authored-by: makseq-ubnt <makseq@gmail.com>

fix: DEV-2406: Fix counters for skipped annotations (#2364)

---

docs/themes/htx/layout/partials/index.ejs

docs: add brew block

---

docs/source/guide/install.md

https://heartex.atlassian.net/browse/DEV-2593

docs: am/DEV-2593: Install LS without internet access

---

label_studio/frontend/src/pages/CreateProject/Config/Preview.js

Update preview in lso to apply selecting by default

fix: DEV-684: Choice Selected True Preview

---

label_studio/core/settings/base.py
label_studio/data_manager/functions.py
label_studio/data_manager/serializers.py
label_studio/tasks/models.py
label_studio/tests/test_api.py

* fix: DEV-2687: Display source filename for S3 objects
* Move storage filename to separate field (DEV-2687)

fix: DEV-2687: Display source filename for S3 objects (#2555)

---

.gitignore
docs/source/tags/brush.md
docs/source/tags/brushlabels.md
docs/source/tags/collapse.md
docs/source/tags/datetime.md
docs/source/tags/ellipse.md
docs/source/tags/ellipselabels.md
docs/source/tags/hypertextlabels.md
docs/source/tags/image.md
docs/source/tags/keypoint.md
docs/source/tags/keypointlabels.md
docs/source/tags/label.md
docs/source/tags/labels.md
docs/source/tags/list.md
docs/source/tags/number.md
docs/source/tags/pairwise.md
docs/source/tags/paragraphlabels.md
docs/source/tags/polygon.md
docs/source/tags/polygonlabels.md
docs/source/tags/ranker.md
docs/source/tags/rating.md
docs/source/tags/rectangle.md
docs/source/tags/rectanglelabels.md
docs/source/tags/relation.md
docs/source/tags/relations.md
docs/source/tags/repeater.md
docs/source/tags/shortcut.md
docs/source/tags/taxonomy.md
docs/source/tags/textarea.md
docs/source/tags/timeserieslabels.md

Brush, Collapse and Repeater tags missed from docs.

docs: Fix tags in gitignore; add missed tags

---

docs/source/guide/frontend.md

As the example code uses 1.x stuff like `onSubmitAnnotation`, the links to the js&css files need to be updated as well...

docs: Update frontend docs to latest unpkg

---

docs/source/guide/quality.md

[DEV-3292]
[DEV-3292]: https://heartex.atlassian.net/browse/DEV-3292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Fix URL link to point to LS App

---

docs/source/guide/labeling.md

[DEV-3360]
[DEV-3360]: https://heartex.atlassian.net/browse/DEV-3360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Added ENT tag for Outliner section

---

docs/source/guide/custom_metric.md

[DEV-3160]
[DEV-3160]: https://heartex.atlassian.net/browse/DEV-3160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Add custom tags assignment for Custom Agreement metric

---

label_studio/data_manager/functions.py

Reverts heartexlabs/label-studio#2976

feat: revert: DEV-3372: Add "video" type to the Data Manager columns API

---

docs/source/guide/labeling.md

[DEV-3471]
[DEV-3471]: https://heartex.atlassian.net/browse/DEV-3471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Add content for multiple BB creation

---

docs/source/tags/repeater.md

[DEV-3503]
[DEV-3503]: https://heartex.atlassian.net/browse/DEV-3503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Add mode property in Repeater Tag page

---

deploy/requirements.txt

Reverts heartexlabs/label-studio#3014

Revert "fix: DEV-3513: Revert google deps"

---

label_studio/organizations/api.py
label_studio/organizations/serializers.py

…ivated. Projects, displayed on user's organization page, include other organizations

fix: DEV-3239, DEV-3465: Data manager is broken if annotator is deactivated

---

docs/source/guide/labeling.md

[DEV-3479]
[DEV-3479]: https://heartex.atlassian.net/browse/DEV-3479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Add GIF border for images in labeling page

---

docs/source/guide/storage.md

[DEV-3028]
[DEV-3028]: https://heartex.atlassian.net/browse/DEV-3028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Add note insructions to storage page

---

docs/source/guide/release_notes.md

[DEV-3665]
[DEV-3665]: https://heartex.atlassian.net/browse/DEV-3665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Release Notes for Label Studio Enterprise 2.3.1

---

docs/themes/v2/layout/home.ejs

[DOC-90]
[DOC-90]: https://heartex.atlassian.net/browse/DOC-90?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Update the welcome message on the landing page

---

deploy/requirements.txt
label_studio/io_storages/gcs/models.py

bump google dependencies
(cherry picked from commit 085aa69ac81cc5902df97244ee93b130cafe2acb)

fix: SRE-351: GCS persistent storage is broken (#3335)

---

docs/source/guide/comments_notifications.md

[DOC-98]
[DOC-98]: https://heartex.atlassian.net/browse/DOC-98?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Edit frontmatter for comments page

---

label_studio/users/templates/users/user_account.html

fixes https://github.com/heartexlabs/label-studio/issues/3033

fix: Token renewal button [issue #3033]

---

docs/source/templates/gallery_asr.ejs
docs/source/templates/gallery_conversational_ai.ejs
docs/source/templates/gallery_cv.ejs
docs/source/templates/gallery_data_parsing.ejs
docs/source/templates/gallery_dynamic_labels.ejs
docs/source/templates/gallery_nlp.ejs
docs/source/templates/gallery_rns.html
docs/source/templates/gallery_timeseries.ejs
docs/source/templates/gallery_videos.ejs
docs/source/templates/get_started.md

[DOC-99]
[DOC-99]: https://heartex.atlassian.net/browse/DOC-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Edit the left nav titles on templates page

---

deploy/requirements.txt

* fix: DEV-4092: Pin numpy version
* Update requirements.txt
(cherry picked from commit 7873e2898080bd5c73270984c5254246905a4198)

fix: DEV-4092: Pin numpy version (#3475)

---

docs/package.json
docs/source/guide/manage_users.md

[DEV-1317]
[DEV-1317]: https://heartex.atlassian.net/browse/DEV-1317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Add status info for user accounts
