backend/db.py

Probably in #46 I haven't fully understand how the code should work.
This pull requests fixes the problem, that after adding the first completion for task (which doesn't have file in `output` directory), no `id`, `task_path` and `data` was added.
Now viewing task with completion works like a charm.

Fix completion saving bug where no task's data was saved

---

src/stores/AppStore.js
src/stores/CompletionStore.js

@shevchenkonik For python pep8 convention we should name variables like_this_style but not thisStyle. So, when you send to the server "lead_time" it will be automatically serialized to "completion.lead_time" in python model. The names must be the same.

leadTime renamed to lead_time

---

docs/source/guide/frontend.md

Hi,
I am experimenting with embedding the label studio with [labelbox](https://labelbox.com/) as a [custom editor](https://labelbox.com/docs/custom-interface-sdk/custom-interfaces). It works surprisingly good and I like your editor actually better than the default one. 
But, I found some issues / inconsistencies with the docs. It was very difficult to remove all interaction with the backend... 
- `#editor` -> `editor`: `document.getElementById('editor')` will be called.
- extend `apiCalls` docs, as it was not clear to me, what actually happens.
- extend `explore` docs to highlight interaction with the backend
- consistency: either `expert.pk` or `expert.id`
- consistency: `deleteCompletion` had different description than the other two.

Adjust docs for embedding the frontend

---

docs/package-lock.json
docs/package.json

**Regular Expression Denial of Service (ReDoS)** - Medium Severity
Vulnerable module: marked
Introduced through: hexo-renderer-marked@1.0.1
Fixed in: 0.7.0
**Detailed paths and remediation**
- Introduced through: label-studio-documentation@0.0.1 › hexo-renderer-marked@1.0.1 › marked@0.6.3
- Remediation: Upgrade to hexo-renderer-marked@2.0.0

fix vulnerability in docs

---

label_studio/project.py
label_studio/server.py
label_studio/tasks.py
label_studio/utils/argparser.py

We can't initialize labeling project for some input formats: `text, text_dir, audio_dir, image_dir` if label config file is not explicitly defined

Require some input formats have label config

---

label_studio/utils/uri_resolver.py

- Workaround limitations with signed URLs generated on GCE instance (https://github.com/googleapis/google-auth-library-python/issues/50)

Credentials on GCE

---

label_studio/templates/tasks.html

In order for LS to work behind proxy on non-root url all resources should be loaded by relative paths. These are the only .js files left that use absolute path to load.

Relative paths to .js files

---

README.md

Just a small fix in README:
`label-studio/server.py` -> `label_studio/server.py`

Fix wrong path in README.md

---

label_studio/ml/server.py

When the model_class is specified for a ML backend (aka format script.py:CLASS), server.py was checking too early that the filepath was existing (aka before calling split(":") on the argument)

Fixing path check when model_class is specified

---

label_studio/ml/model.py

Negative ttl is not accepted anymore for rq job ttl. Use None instead

Fix redis enqueue for rq > 1.0

---

label_studio/utils/uploader.py

This will fix e.g. image upload when using custom root dir

Use project path instead of name for uploaded files

---

docs/source/tutorials/dummy_model.md
docs/source/tutorials/pytorch-image-transfer-learning.md
docs/source/tutorials/sklearn-text-classifier.md
label_studio/storage/filesystem.py

otherwise it will replace resolved data url in memory and store that
resolved url in completions. That will not work with ml backends because
presigned urls expire.
Also this makes ExternalTasksJSONStorage semantically same as other
cloudstorages. Specifically you need to use "set" to make changes.

Make deepcopy of values returned from ExternalTasksJSONStorage

---

label_studio/storage/base.py
requirements.txt

The issue:
When a new project is created, a source.json file is created from a task.json file. It would be convenient if the ordering of id's in the task.json file is also maintained in the source.json file. Using an ordered set accomplishes this goal
behaviour in previous versions:
```
task.json:
[id1, id2, id3..., idn]
source.json:
{0 -> id1, 1 -> id2, 2-> id3, n-1 -> idn ...}
```
behaviour in current version:
```
task.json:
[id1, id2, id3..., idn]
source.json (random ordering due to set):
{0 -> id4, 1 -> id10, 2-> id111, n-1 -> id3 ...}
```
The changes in this PR revert the current behaviour to the previous behaviour, i.e. maintain the ordering.
If random ordering is required during annotation, then the sampling configuration should be used rather than changing the composition of the …

Maintain ordering in source.json and task.json

---

label_studio/templates/model.html

Under the page `Model`, button `Start Predictions` and the button that deletes a ML backend don't work in Firefox (they do work fine in Chrome): the POST request is not issued because the page is reloaded.
This PR fixes the UI to reload the page only after the POST completes successfully.

Fix buttons "Start Predictions" and "Remove ML backend" for Firefox

---

label_studio/project.py

Currently, `--sampling=sequential` doesn't really order tasks by id. This PR fixes that.

Fix `--sampling=sequential`

---

label_studio/storage/base.py
label_studio/storage/s3.py
label_studio/tests/uri_regex_test.py
label_studio/utils/uri_resolver.py

This PR add support for embedding pdf files (or other media files) via the HyperText object tag from a cloud storage backend. The type of cloud storage backend (s3 or gs), bucket name and key name are determined via a regular expression. I've added a couple of tests for this regex. 
In addition, users can optionally set a new `presign` parameter via the `--source-params` flag, to indicate whether they want to generate presigned URLs to access their S3 objects and which defaults to true. If using presigned URLs is not deemed sufficiently secure, the `presign` parameter can be set to false, and the URIs are not exchanged for a presigned URL, but for a data string containing the base64-ecoded value of the object that can be rendered in an `<embed />` or `<iframe />` html tag. 
Not sure if …

Add support for resolving s3 uris in html embed tags

---

requirements.txt

Hey, I'm making this simple pull request in order to make the click dependency a bit more relaxed. Currently, this will essentially upgrade click from 7.0.0 to 7.1.2. It will also make it possible to install this package along with other packages (like black) in the same virtualenv which depends on later versions of click.

Specify click dependency with compatible version instead of specific

---

label_studio/utils/misc.py

Add timeout to version check
Fix #558

Fix version checking hang in offline deployment

---

docs/source/guide/api.md
label_studio/blueprint.py

I image most people will save their configs as XML files and then will want to post the XML via the API so I added the ability to post XML to the API.
Also added addition checks on the received API request.
Usage:
Curl Example post local config.xml
`curl -X POST -H Content-Type:application/xml http://localhost:8080/api/project/config \
--data @config.xml`
Python Example:
```
xml = """<View>
<Header value="Select label and start to click on image"></Header>
<Image name="image" value="$image"></Image>
<PolygonLabels name="label" toName="image" strokeWidth="3" pointSize="small" opacity="0.9">
<Label value="Airplane" background="red"></Label>
<Label value="Car" background="blue"></Label>
</PolygonLabels>
</View>"""
headers = {'Content-Type': 'application/xml'} …
```

Add xml config to api

---

label_studio/blueprint.py

The current code ` if not input_args.debug and check_port_in_use('localhost', port):` is checking whether the port (e.g. default :5000) is in use and then adds +1, but checks only once. If a user has a range of ports in use, for example 5000-5002, `label studio` does not manage to find an open port.
Modified by moving `check_port_in_use()` into a while loop to continue the check until there is a free port `label studio` can use.
I also took the freedom to create a PR without opening an issue first, hope that is fine with you.

Add while loop to check for more busy ports

---

label_studio/tests/e2e_actions.py
label_studio/utils/misc.py

Hello, I encountered UnicodeDecodeError caused by a [configuration example in repository](https://github.com/heartexlabs/label-studio/blob/bf71ea49478f6a84560880a621f5181abc8e85c4/label_studio/examples/ts_rel_text/config.xml#L33). 
For arbitrary configuration files, I added encoding type into project configuration opener, and also modified several test codes.
I don't know if it's appropriate to send PR into `0.9.1.post2`. If I should send PR into other branch, please notice me. 
Please take a look. 😄
resolve #642

Small but critical initial configuration encoding error fixed.

---

docs/source/guide/install.md
docs/source/guide/labeling.md
docs/source/guide/predictions.md
docs/source/guide/signup.md
docs/source/guide/start.md
docs/source/guide/storage.md
docs/source/guide/tasks.md

Slack feedback and some cleanup of links and such. 
* Adding intro sentence and fixing links to point to PostgreSQL section in install docs
* Fixing an updated screenshot ref
* Added info about accounts in response to slack questions
* Fixed docs bug about how to sync cloud storage (manual, not auto)
* Updated migration guidance with more info
* Fixed a couple mentions of completions that I'd missed somehow

Update docs based on feedback

---

docs/source/guide/frontend_reference.md
docs/source/guide/index.md
docs/source/guide/install.md
docs/source/guide/ml.md
docs/source/guide/setup.md
docs/source/guide/start.md
docs/source/guide/tasks.md

fixing link syntax typos in ML doc

fixing link typos

---

label_studio/io_storages/localfiles/models.py

When syncing a local storage with subfolders, the server will try to import the images in these folders as if they were at the root of the storage, and thus will fail to retrieve them.
This PR fixes this issue by simply yielding the full path to the images as keys instead of just their names (don't know if there's any better way to do it but this works and doesn't seem to break anything else).

Fix wrong file path being checked when trying to sync images from local storage subfolders

---

label_studio/io_storages/gcs/models.py

While trying to connect with the GCS bucket, I was able to successfully read the number of objects in the bucket, however, the data was not loading from the bucket. Following is the stack trace. 
> [2021-04-14 12:05:06,472] [core.utils.common::custom_exception_handler::85] [ERROR] 4c589210-8293-4c0e-a05f-4750defe5a9a Error calling the IAM signBytes API: b'{n  "error": {n    "code": 400,n    "message": "Request contains an invalid argument.",n    "status": "INVALID_ARGUMENT"n  }\\n}n'Traceback (most recent call last):File "/home/lordzuko/miniconda3/envs/label-studio/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatchresponse = handler(request, *args, **kwargs)File "/home/lordzuko/miniconda3/envs/label-studio/lib/python3.8/site-packages/label_studio/data_manager/api.p …

Changed service account email to None as the default service account was resulting in an invalid argument

---

docs/source/guide/start.md

1. Fix typo of environment variable for data directory.
Signed-off-by: Even Wei <evenwei@infuseai.io>

Fix typo of data dir env

---

label_studio/io_storages/base_models.py

```Fix: JSONs which were present in S3 tasks were not being parsed correctly. They were getting created as nested JSONs where the entire data went into the data field. Also there would have been bugs, had `predictions` or `annotations` field been found in the json field. ```

FIX: S3 Import issue causing nested jsons

---

label_studio/projects/api.py

* Users get first non-expired task in external prepared tasks (from data manager)
* When task locked by user expires or user did not locked any task from project, they receive an unlocked task
Fixes #795
/cc @makseq

Fix distinct collaborators receiving the same task from project

---

docker-compose.yml

At least in my usage, static asset files were invisible to nginx when using docker-compose. This led to 404 GET errors and the label-studio frontend not loading. Made it so the label-studio container shares the static directory with the nginx container.

Share static volume between label-studio and nginx containers

---

scripts/serve_local_files.sh

Currently, the `OUTPUT_FILE` and `PORT` variables are assigned from the same command argument `$3`. Since, `PORT` is declared after `OUTPUT_FILE `, I believe it was intended for `PORT` to get its value from the 4th argument `$4`.

Fixes PORT variable's argument index

---

docs/source/guide/ml.md

The Quickstart step 3 says to "Start the ML backend server", but the current command is for starting label-studio with a new project and attaching an existing, already running backend. With the current command, the later step 6 fails as there is no running backend at http://localhost:9090.
```
label-studio start my_ml_backend --init \ 
--ml-backends http://localhost:9090
```
The updated command will start the label-studio-\*ml\* backend server (i.e. http://localhost:9090).
```
label-studio-ml start my_ml_backend
```
Then in step 6, the link to `http://localhost:9090` will be valid.

quickstart start ml backend instruction fix

---

deploy/docker-entrypoint.sh
deploy/wait-for-postgres.sh

Issue with docker-compose at startup.
app container is not starting label-studio: `wait-for-postgres.sh`, after checking the postgres service, executes `bash`, this prevents `docker-entrypoint.sh` from executing the rest of the commands that should start label-studio app.

Fix docker-compose startup (#1004)

---

label_studio/projects/templates/projects/settings.html

Project title/description/instructions are used in django templates to non-react pages. Escape them for safety

Escape multiline description/instructions in tpl

---

label_studio/projects/models.py

In some cases (e.g. bulk removals of tasks/annotations) project summary is not updated correctly. This workaround helps to keep the project summary consistent with empty projects

Ensure project summary consistent on project saving/validation

---

label_studio/tasks/serializers.py
label_studio/tests/data_import.tavern.yml
label_studio/tests/shared_stages.yml
label_studio/tests/test_suites/samples/previous_export.json

This PR solves the "Unknown completed_by ID" validation error when we try to import previously exported JSON tasks, by match existing users given emails:
- if completed_by is omitted - it will assign annotations to the user who imports or user who created this project
- if completed_by is dict object - it will look for `"email"` field inside and raise validation error instead
- if completed_by is integer (deprecated format) - it will try to match existing annotator's ID and raise validation error if not found

Validate annotators emails when import previous exports

---

.gitattributes

Workaround for known issue in docker-win: https://github.com/docker/for-win/issues/1340
Fixes: https://label-studio.slack.com/archives/CQ8LYPPJS/p1626704725265900

Configure .gitattributes to handle line endings on windows

---

README.md

Incorrect paths were used in the root readme for applying frontend changes, likely due to outdated documentation. This PR updates the paths in order to allow the commands to succeed when run locally.

Fix frontend paths in root readme

---

deploy/requirements.txt

- TextArea with single text item now simplified as simple string (e.g. like in audio transcription case)
- `created_at`, `updated_at` & `lead_time` now added to JSON_MIN, CSV, TSV export formats

[ext] Prettify TextArea export & add created/updated_at and lead_time

---

docs/source/guide/FAQ.md
docs/source/guide/api.md
docs/source/guide/quality.md
docs/source/guide/setup_project.md
docs/source/guide/start.md
docs/source/guide/tasks.md

Fixing broken links to API docs
Improving small things in local storage that were confusing
Added info about markup in instructions
Added cross-links to help information findability

Small doc fixes

---

label_studio/data_export/api.py
label_studio/tests/export.tavern.yml

- use `curl -X GET http://localhost:8080/api/projects/123/export?ids[]=38319\&ids[]=38321` to export only specific tasks
- set JSON exportType by default

[ext] Allow exporting specific task IDs

---

deploy/requirements.txt
label_studio/core/settings/base.py

When running label-studio on Google Cloud Run, the logs don't get formatted properly with the correct severity.
Solution is to set up the `google.cloud.logging.Client` in `LOGGING` configs if `GOOGLE_LOGGING_ENABLED` env var is enabled.
Tested enabling and disabling GOOGLE_LOGGING_ENABLED.
Running label-studio locally:
```
python label_studio/manage.py runserver
```
Building docker image locally:
```
docker build .
```
Building and deploying it remotely on Google Cloud Build and Google Cloud Run:
```
gcloud builds submit --tag gcr.io/maystra-poc/label-studio
gcloud run services describe label-studio --region us-central1
```

Google Cloud Logging handler

---

label_studio/data_export/api.py

The current API examples to export to an 'annotations.json' file were not working due to a missing quote at the start of the string.

[fix] Correct Export API examples

---

label_studio/core/settings/base.py

On https://github.com/heartexlabs/label-studio/pull/1369 I introduced a flag in settings to enable/disable google logging. It should have been using get_bool_env instead of get_env.
This PR fixes it as well as adds a logging line to help debugging if the handler is enabled or not.

Using get_bool_env to check for flag in core.settings

---

deploy/docker-entrypoint.d/10-wait-for-postgres.sh

If the DB name is not `root`, then we cannot to the DB.
Add the bash substitution arg to `POSTGRE_NAME` so we can set the name of the DB using env. vars

Specify DB name in initialization script

---

label_studio/frontend/src/providers/ApiProvider.js

This is a minor fix, but the file modal sets the key `simple` twice.

Fixing duplicate key simple in ApiProvider

---

docs/source/guide/webhook_reference.md
label_studio/projects/serializers.py

All webhook event payloads include total number of tasks, total annotated tasks, total annotations, and more. Updated the table in the event reference (not the examples) to include names and descriptions.

Update webhook event reference to include number fields

---

README.md

The Markdown for the Docker Hub link in `README.md` was using inverted syntax so it wasn't rendering properly.

Fix link Markdown and typo

---

label_studio/ml/models.py

Tickets: 
- https://github.com/heartexlabs/label-studio-ml-backend/issues/64
- #1755

Fixed the two times predict call issue for single task prediction

---

label_studio/core/label_config.py

There is a bug in <Relations> and <Relation> tag parsing. When parsed as label_config parameter of LabelStudioMLBase, relation tags were ignored.
Take the default relation extraction template as an example. 
```
<View>
<Relations name="rel_label" toName="text">
<Relation value="org:founded_by"/>
<Relation value="org:founded"/>
</Relations>
<Labels name="label" toName="text">
<Label value="Organization" background="orange"/>
<Label value="Person" background="green"/>
<Label value="Datetime" background="blue"/>
</Labels>
<Text name="text" value="$text"/>
</View>
```
The above xml template will be parsed by parse_config util function as following json. \
```
{
"label": {
"type": "Labels",
"to_name": [
"text"
],
"inputs": [{
"type": "Text",
"value": "text"
}],
"labels": [
"Organization", …
```

Include <Relation> tag as label

---

docs/themes/htx/source/js/common.js

`initLocationHashFuzzyMatching` should be running after the page loads

[fix] docs jumping to wrong anchor at the load (DEV-1258)

---

docs/source/guide/FAQ.md
docs/source/guide/predictions.md

Add notes in troubleshooting spots about what to do if pre-annotations aren't visible to annotators, since we've had a number of questions about this lately.

Add pre-annotation troubleshooting 

---

README.md
docs/source/guide/install.md

Pillow upgrade to 9.0.0 means Python 3.6 is no longer supported by Label Studio

Remove support for Python 3.6 from docs

---

.github/workflows/tests.yml
deploy/requirements.txt

fix: DEV-1525: update label-studio-converter with conll, pillow & nltk version bumps. Remove python 3.6 from tests

---

docs/source/guide/predictions.md

- Add pre-annotations example for OCR
- Add more resources and links for creating your own pre-annotations format based on your labeling configuration.
- Add structure to make existing examples easier to find on the page
Coming soon but not in this PR:
- More guidance for generating appropriate pre-annotations format from an ML backend
- More clarity about where to put prediction scores (and a dedicated header to make that information more findable)

docs: DEV-1463 - Add more examples for prediction formats

---

docs/source/guide/FAQ.md
docs/source/guide/storage.md
docs/source/guide/tasks.md

Fixing some small things I noticed:
- broken link on tasks page
- missing xlinks across troubleshooting
- stylistically inconsistent and somewhat confusing section on storage page

Docs: Fix small docs bugs

---

docs/source/templates/audio_regions.md
docs/source/templates/automatic_speech_recognition_segments.md
docs/source/templates/image_bbox.md
docs/source/templates/named_entity.md
docs/source/templates/sentiment_analysis.md

Enhanced the following templates with the corresponding templates from playground:
- Text Classification / Sentiment Analysis with Text > Multi Classification 
- Named Entity Recognition with Text > Word Alignment and Per Region > Text spans labeling 
- Automatic Speech Recognition with Segments with Per Region > Audio Regions Example
- Object Detection with bboxes with Per Region > Image bboxes labeling
Chose to describe the specific parts of the templates that were different rather than posting entirely new labeling configs that were largely the same but slightly different. Instead, focused on just the parts that were different and explained those.
More updates to come!

Docs: DEV-1511 — Enhance relevant templates with playground templates

---

docs/source/guide/label_studio_compare.md

- Address misleading ✔️ vs ❌ in the on-prem hosting row by changing hosting to deployment and updating the check mark
- Add some extra links to the table
- Remove a duplicate row

DOCS: Fix confusion with the label studio compare page

---

docs/source/templates/activity_recognition.md
docs/source/templates/change_point_detection.md
docs/source/templates/outliers_anomaly_detection.md
docs/source/templates/signal_quality.md
docs/source/templates/time_series.md
docs/source/templates/time_series_forecasting.md

* Streamline interactive template presentation
* Add details about all labeling configs
* Streamline input format examples for generic time series
* Add "enhance this template" section to generic time series to restructure other examples

Docs: DEV-1717 — Enhance time series templates

---

docs/source/templates/image_captioning.md
docs/source/templates/image_classification.md
docs/source/templates/named_entity.md
docs/source/templates/sentiment_analysis.md
docs/source/templates/text_summarization.md

- Add sticky header example to image caption template
- Add sticky left column example to image classification template 
- Add filter example to NER template
- Add three column labeling to text classification template and fix up multi-classification example
- Add scrollbar with long text example to text summarization template
- Add related templates to text classification template

DOCS: DEV-1511 — Add more playground template enhancements

---

label_studio/io_storages/localfiles/models.py

For better control of imported tasks, file reading has been changed to ascending order of filenames.
In other words, the task IDs are sorted by filename order.
Issue described in detail [here](https://github.com/heartexlabs/label-studio/issues/2266).

fix: DEV-2266: Tasks ordered by file names on import

---

label_studio/data_manager/actions/experimental.py

This PR adds the `Add Or Modify Data Field" action in the Data Manager.
**Number**
Add new data field with float value.
**String**
Add new data field with string value.
**Expressions**
* permutative sampling:
```
sample()
> sample()  # => if N_tasks=4 => 4, 1, 3, 2 
```
* uniform random from min integer to max integer:
```
random(<min_int>, <max_int>)
> random(1, 3)  # => 1, 3, 2, ..., N_tasks
```
* random sampling for string or integer choices with weights: 
```
choices(["<value1>", "<value2>", ...], [<weight1>, <weight2>, ...])
> choices(["a", "b"], [0.4, 0.6])  # => "a", "b", "b", "b", ..., N_tasks
```
* replace old substring to the new substring:
```
replace("old-string", "new-string")
> replace("a", "b")  # => abc => bbc
```

feat: Experimental feature Add data field

---

label_studio/data_import/models.py

This is the issue: https://github.com/heartexlabs/label-studio-frontend/issues/733
----
I am using label-studio with the `--host` parameter like this:
```
$ label-studio --host https://openbayes.com/jobs/abc/proxy/8080
```
Every thing works good until I import some images for ocr task. It seems that the generated urls in frontend have more than one `/` between the prefix and the upload path:
If I mannully remove the extra `/` in the 
```
/jobs/open-tutorials/jobs/proxy/8080 ---->//<---- data/upload/1/df0703be-AAMU4003561_45R1__011_0741_181125_224515_01_Manual_1.jpg
```
the url can access successfully.

fix: Remove extra slash for file url

---

label_studio/io_storages/localfiles/models.py

Fix for issue #2291 
This fix allows for local files with characters like "+", etc. in the relative path to be displayed.
e.g. cat+dog.png

fix: Quote relative path

---

label_studio/server.py

Fix #1719
If enabled, set the `journal_mode` to `WAL` upon creation for SQLite.

Enable SQLite on Azure App Services

---

label_studio/data_import/uploader.py
label_studio/tests/data_import/test_uploader.py

LS users are able to use data import functionality to access local files on the running system, including environment variables, etc. This is achieved by using `file://` url schema (ie. `file:///etc/passwd`).
Submitting a URL like this will cause Label Studio to fetch the local file and add it to the project, which can then be accessed in the `/data/uploads` folder.
https://heartex.atlassian.net/browse/DEV-3212

fix: DEV-3212: Add validation to avoid users import local files using URL

---

docs/source/guide/export.md
label_studio/core/argparser.py
label_studio/data_export/mixins.py
label_studio/server.py
label_studio/tasks/functions.py
label_studio/tests/tasks/test_functions.py

These changes add a new command to export a Label Studio project in a specific format.
`label-studio export <project-id> <export-format>`
- The file generated will be saved inside `settings.EXPORT_DIR` folder.
- All the project tasks will be included in the process.
- Default values will be used to flags like `INTERPOLATE_KEY_FRAMES` and `CONVERTER_DOWNLOAD_RESOURCES` defined in the settings file.
https://heartex.atlassian.net/browse/DEV-3145

feat: DEV-3145: Add command for export project in Opensource

---

label_studio/data_manager/api.py
label_studio/tests/data_manager/test_views_api.py

Tabs are being randomly mixed after label stream. It's not guaranteed that backend will always return in the expected order. 
These changes add an ASC ID ordering in the view class to avoid this issue.
https://heartex.atlassian.net/browse/DEV-1947

fix: DEV-1947: Fixed tabs randomly mixed after label stream

---

docs/source/guide/release_notes.md

[DEV-3495]
[DEV-3495]: https://heartex.atlassian.net/browse/DEV-3495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs: Removed ENT tag from Release Notes info section

---

deploy/requirements.txt

Fixes issue https://github.com/heartexlabs/label-studio/issues/3220 by bumping to `Django==3.2.16` that fixed two CVEs related to Django.
I followed [what was done here when it was last updated to `3.2.14`](https://github.com/heartexlabs/label-studio/pull/2706)
I only have a Mac so I tested locally with `sqlite` and one of the tests (see below) failed for the `develop` base branch when I pulled from the most recent -- yet I don't see a failed build on GitHub 🤔. All other tests passed.
Therefor I'm not sure if my test setup was correct. I tried following both `README` to install and then copied how GItHub workflow script setup the testing env to no avail. This may not be an issue though.
```
FAILED tests/test_api.py::test_creating_activating_new_ml_backend[201-http://my.super.ai-4] - …
```

fix: Issue 3220 Update Django version for CVEs

---

docs/source/includes/image_units.md

Current example python code references 'completed' instead of 'annotations' in array reference that errors out upon running the code.

docs: updated python example code for unit conversion referenced in documentation

---

label_studio/core/utils/common.py
label_studio/tasks/migrations/0009_auto_20210913_0739.py
label_studio/tasks/migrations/0017_new_index_anno_result.py

…existing (#3384)
fix: DEV-3839: Avoid creation of pg_trgm in postgres if it's already exists

fix: DEV-3839: Avoid creation of pg_trgm in postgres if it's already existing

---

label_studio/io_storages/base_models.py

Per request here: https://github.com/heartexlabs/label-studio/issues/2852
Bug when importing an annotated json file from azure storage. Using sample from https://labelstud.io/guide/tasks.html#Example-JSON-format

fix: Sync storage with annotations when was_cancelled is not defined

---

docs/source/blog/6-costly-data-labeling-mistakes-and-how-to-avoid-them.md
docs/source/blog/Automate-your-ML-pipeline-with-Label-Studio-and-Amazon-SageMaker.md
docs/source/blog/Improve-OCR-quality-with-Tesseract-and-Label-Studio.md
docs/source/blog/release-050.md
docs/source/guide/frontend.md
docs/source/tags/number.md
docs/source/templates/intent_classification.md
docs/source/templates/inventory_tracking.md
docs/source/templates/multi-page-document-annotation.md
docs/source/templates/taxonomy.md
label_studio/annotation_templates/natural-language-processing/taxonomy/config.xml
label_studio/core/feature_flags/README.md
label_studio/core/settings/base.py
label_studio/core/storage.py
label_studio/core/utils/common.py
label_studio/frontend/README.md
label_studio/io_storages/redis/models.py
label_studio/projects/api.py
label_studio/projects/migrations/0001_squashed_0065_auto_20210223_2014.py
label_studio/projects/models.py
label_studio/server.py
label_studio/tasks/models.py
label_studio/tests/test_invites.py
label_studio/tests/test_predictions.py
label_studio/tests/test_project_validation.py
label_studio/webhooks/utils.py

an extract from https://github.com/heartexlabs/label-studio/pull/3515 
Minor note that commit 93aa0d9b8a697f4ece6f1d46036f8976d7aafaf7 would no longer be `datalad rerun`-able since codespell configuration is no longer present in the PR.  I didn't bother rewriting commit message there though.
I also left out one commit which was not a typo fix but a workaround for `codespell`.

fix: Typos identified by codespell

---

scripts/serve_local_files.sh

if there is a space in `INPUT_DIR`, then `$INPUT_DIR` will expand to two strings, giving an error in the CD command. Wrapping the expansion in quotes fixes this.

Expand bash variable in quotes to avoid expansion errors

---

.codespellrc
.github/workflows/codespell.yml
docs/source/guide/webhook_reference.md

Please check the diff carefully, but interestingly it also feels to provide a "bug fix"  in https://github.com/heartexlabs/label-studio/compare/develop...yarikoptic:label-studio:enh-codespell?expand=1#diff-de230f8c6422148eba24cf335d041aa51a20c329de9c1953ae201a5d1b2cc84f for "properties" typo fix?

fix: Codespell configuration and github action workflow
